config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  # Admin namespace:
  namespace :admin do
    # (app/controllers/admin/blog/articles_controller.rb)
    scope module: 'blog' do
      resources :articles
      get 'tags/:tag', to: 'articles#index', as: :tag
      resources :categories
    end

    scope module: 'visitors' do
      resources :users
    end

    root 'dashboard#index'
  end

  scope module: 'visitors' do
    resources :users
    resource :sessions, only: [:new, :create, :destroy]
  end

  scope module: 'blog' do
    resources :articles, only: [:index, :show]
  end

  root 'dashboard#index'
end

app/views/admin/common/_empty_resource.html.haml
%blockquote
  %p= "There are no #{controller.controller_name} in your request :/"
  %footer
    Try change your resource params or
    = link_to 'step back', :back

app/views/admin/common/_flash.html.haml
- flash.each do |key,value|
  = content_tag(:p, "Сообщение: #{value}", class: "lead text-center flash bg-danger")

app/views/admin/common/_header.html.haml
.container-fluid
  .navbar-header
    = link_to 'Blog ->', root_path, class: 'navbar-brand'
  .navbar-collapse.collapse
    %ul.nav.navbar-nav.navbar-right
      %li
        = link_to 'Dashboard', root_path
      %li
        = link_to 'Manage Articles', admin_articles_path
      %li
        = link_to 'Manage Users', admin_users_path, class: 'blog-nav-item'
      %li
        %a.blog-nav-item{href: '#'} Help
      - if user_sign_in?
        %li.dropdown
          %a.dropdown-toggle{href: '#', data: { toggle: "dropdown" }}
            Profile
            %b.caret
          %ul.dropdown-menu
            %li.dropdown-header Login :
            %li= link_to current_user.login, current_user
            %li.divider
            %li.dropdown-header Email :
            %li= link_to current_user.email, current_user
            %li.divider
            %li.dropdown-header Access :
            %li= link_to current_user.role.name, '#'
            %li.divider
            %li.dropdown-header Quit :
            %li= link_to "Exit", sessions_path, method: :delete

app/views/admin/common/_sidebar.html.haml
%h3.text-info Users :
%ul.nav.nav-sidebar
  %li= link_to "All users", admin_users_path
%h3.text-info Articles :
%ul.nav.nav-sidebar
  %li= link_to "Blog Categories", admin_categories_path
  %li= link_to "All articles", admin_articles_path
  %li= link_to "Unpublished articles", admin_articles_path(published: false)
  %li= link_to "Add article", new_admin_article_path