config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  # Admin namespace:
  namespace :admin do
    # (app/controllers/admin/blog/articles_controller.rb)
    scope module: 'blog' do
      resources :articles
      get 'tags/:tag', to: 'articles#index', as: :tag
      resources :categories
    end

    scope module: 'visitors' do
      resources :users
    end

    root 'dashboard#index'
  end

  scope module: 'visitors' do
    resources :users
    resource :sessions, only: [:new, :create, :destroy]
  end

  scope module: 'blog' do
    resources :articles, only: [:index, :show]
  end

  root 'dashboard#index'
end

app/models/article.rb
class Article < ActiveRecord::Base
  include DataHandler
  include Searchable

  # Assosiation macros
  # -----------------------------------------------------------
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  belongs_to :category
  has_many :taggings
  has_many :tags, through: :taggings

  # Validation macros
  # -----------------------------------------------------------
  validates :title,
            presence:   true,
            uniqueness: { case_sensitive: true },
            length:     { maximum: 255 }
  validates :contents,
            presence:   true

  # Scopes
  # -----------------------------------------------------------
  scope :archive,             -> (archive)  { where archive: archive }
  scope :published,           -> (published){ where published: published }
  scope :starts_with_title,   -> (title)    { where('title like ?', "#{title}%") }
  scope :blog,                -> {
    select(:id, :title, :author_id, :created_at, :contents).archive(false).published(true)
  }
  scope :filter,              -> (name) {
    joins(:category).where('categories.name = ?', name) if name.present?
  }

  # Delegator macros
  # -----------------------------------------------------------
  delegate :name, to: :category, prefix: true

  def all_tags=(names)
    self.tags = names.split(';').map do |t|
      Tag.where(name: t.strip).first_or_create!
    end
  end

  def all_tags
    tags.map(&:name)
  end

  def self.tagged_with(name)
    Tag.find_by_name!(name).articles
  end

  def self.tag_counts
    Tag.select('tags.name, count(taggings.tag_id) as count').joins(:taggings).group('taggings.tag_id, tags.name')
  end
end

app/controllers/admin/blog/articles_controller.rb
class Admin::Blog::ArticlesController < Admin::ApplicationController
  before_filter only: [:show, :edit, :update, :destroy] { |m| m.find_article params[:id] }

  def new
   @article = Article.new 
  end

  def create
    @article = @current_user.articles.new(article_params)
    if @article.save
      redirect_to admin_article_url(@article), notice: 'Article created!'
    else
      render :new
      flash.now[:error] = 'An error ocured on create article!'
    end
  end

  def show
  end

  def index
    if params[:tag]
      @articles = Article.tagged_with(params[:tag])
    else
      @articles = Article.includes(:category).
        search(params.slice(:archive, :starts_with_title)).
        filter(params[:filter]).
        all
    end
    @categories = Category.all
  end

  def destroy
    @article.destroy
    redirect_to admin_articles_url, notice: 'Article deleted!'
  end

  protected

    def article_params
      params.require(:article).permit(:title, :category_id, :contents, :all_tags)
    end

    def find_article id
      @article = Article.find(id)      
    end
end

app/controllers/admin/blog/categories_controller.rb
class Admin::Blog::CategoriesController < Admin::ApplicationController
  before_filter only: [:show, :edit, :update, :destroy] { |m| m.find_category params[:id] }

  def index
    @categories = Category.search(params.slice(:display, :starts_with_name)).all
  end

  def show
  end

  def edit
  end

  def update
    if @category.update_attributes(category_params)
      redirect_to admin_category_url(@category), notice: 'Category updated!'
    else
      render :edit
      flash.now[:error] = "Can't update category attributes!"
    end
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to admin_category_url(@category), notice: 'Category successfully created!'
    else
      render :new
      flash.now[:error] = 'Error on create category!'
    end
  end

  def destroy
    @category.destroy
    redirect_to admin_categories_url, notice: 'Category removed!'
  end

  protected

    def find_category id
      @category = Category.find(id)      
    end

    def category_params
      params.require(:category).permit(:name, :display)
    end
end

app/controllers/blog/articles_controller.rb
class Blog::ArticlesController < ApplicationController
  respond_to :json

  def index
    articles = Article.blog

    respond_with(articles) do |format|
      format.json { render json: articles.as_json }
    end
  end
end

app/views/admin/blog/articles/_article.html.haml
%tr
  %td
    = link_to article.title, admin_article_path(article)
  %td
    = truncate  article.contents, 
                length: 600,
                separator: '/>',
                omission: '...',
                escape: false
  %td
    = link_to article.category_name, admin_category_path(article.category)
  %td
    %span.label.label-warning
      = article.archive
  / %td
  /   %span.label.label-primary
  /     = article.tags.map { |t| t.name }.join(', ')
  %td
    %span.label.label-primary
      = article.published
  %td
    = date_format article.created_at
  %td{colspan: 3}
    = link_to admin_article_path(article), class: 'btn btn-default btn-xs' do
      %i.glyphicon.glyphicon-new-window
    = link_to admin_articles_path(article), method: :delete, class: 'btn btn-danger btn-xs', confirm: "Are you sure to delete #{article.title}?" do
      %i.glyphicon.glyphicon-trash
    / = link_to 'Edit', edit_admin_articles_path(article), class: 'btn btn-primary btn-xs'

app/views/admin/blog/articles/_form.html.haml
= form_for [:admin, @article], html: { class: 'form-horizontal', role: 'form' } do |f|
  = render 'common/errors', object: @article if @article.errors.any?
  .form-group
    = f.label :title, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :title, class: 'form-control'
  .form-group
    = f.label :category_id, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.collection_select :category_id, Category.all, :id, :name, {}, class: 'form-control'
  .form-group
    = f.label :contents, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.cktext_area :contents, ckeditor: { uiColor: "#14B8C4", toolbar: "mini"}, class: 'form-control'
  .form-group
    = f.label :all_tags, "Tags (Enter tags separeted by ';')", class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :all_tags, class: 'form-control'
  .form-group
    .col-sm-10.col-sm-offset-2
      = f.submit class: 'btn btn-default'
      = link_to 'Cancel', :back, class: 'btn btn-danger'

app/views/admin/blog/articles/_search.html.haml
.btn-group
  %a.btn.btn-default{href: "#{admin_categories_path}"}
    Results, articles
    %span.badge= @articles.size
.btn-group
  %button.btn.btn-default Articles display:
  %button.btn.btn-default{data: { toggle: 'dropdown' }}
    %span.caret
    %span.sr-only Article display
  %ul.dropdown-menu{role: 'menu'}
    %li= link_to 'Arhived',     admin_articles_path(archive: true)
    %li= link_to 'Unarhived',   admin_articles_path(archive: false)
    %li= link_to 'Published',   admin_articles_path(published: true)
    %li= link_to 'Unpublished', admin_articles_path(published: false)
    %li.divider
    %li= link_to 'All articles', admin_articles_path
.btn-group
  %button.btn.btn-default Articles category:
  %button.btn.btn-default{data: { toggle: 'dropdown' }}
    %span.caret
    %span.sr-only Article categories
  %ul.dropdown-menu{role: 'menu'}
    - @categories.each do |category|
      %li= link_to category.name, admin_articles_path(filter: category.name)
    %li.divider
    %li= link_to 'All articles', admin_articles_path
.pull-right
  = form_tag admin_articles_path, method: :get, class: 'form form-inline', role: 'form' do
    = text_field_tag :starts_with_title, params[:starts_with_title], class: 'form-control', placeholder: 'title like...'
    = submit_tag 'Search', class: 'btn btn-success'

app/views/admin/blog/articles/_tags_cloud.html.haml
.row-fluid
  .panel.panel-primary
    .panel-heading
      .panel-title
        Tag cloud
    .panel-body
      - tag_cloud Article.tag_counts do |tag, css|
        = link_to tag.name, admin_tag_path(tag.name), class: css

app/views/admin/blog/articles/index.html.haml
%h2 Articles
%hr
/ Articles search
= render 'search'
%hr
/ Tags cloud
= render 'tags_cloud'
/ Articles list
.panel.panel-default
  / Panel contents
  .panel-heading List of articles :
  / Table
  - unless @articles.blank?
    %table.table.table-hover
      %thead
        %th Title :
        %th Article preview :
        %th Category
        %th Archive
        %th Published
        %th Created :
        %th{colspan: 3} Action
      %tbody
        = render @articles
  - else
    = render partial: 'admin/common/empty_resource'
= link_to new_admin_article_path, class: 'btn btn-lg btn-success' do
  %i.glyphicon.glyphicon-pencil Add

app/views/admin/blog/articles/new.html.haml
%h2
  %i.glyphicon.glyphicon-plus
  Add Article
%hr
= render 'form'

app/views/admin/blog/articles/show.html.haml
.container-fluid
  %ul.nav.nav-tabs
    %li.active
      %a.active{data: {toggle: 'tab'}, href: '#all'} All
    %li
      %a{data: {toggle: 'tab'}, href: '#article'} Article
    %li
      %a{data: {toggle: 'tab'}, href: '#comments'} Comments
  .tab-content
    .tab-pane.fade.active.in#all
      %h1
        = @article.title
        %small= @article.published? ? 'published' : 'unpublished'
        - if @article.archive?
          %span.label.label-warning archived
      %hr
        = @article.contents.html_safe
      .row
        .pull-left.col-sm-6.col-md-6
          Tags :
          = raw @article.all_tags.map { |t| link_to t, admin_tag_path(t) }.join(', ')
        .pull-right.col-sm-6.col-md-6
          Views :
          %span.label.label-info
            = @article.views
      %hr
      %h3 Comments