config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  # Admin namespace:
  namespace :admin do
    # (app/controllers/admin/blog/articles_controller.rb)
    scope module: 'blog' do
      resources :articles
      get 'tags/:tag', to: 'articles#index', as: :tag
      resources :categories
    end

    scope module: 'visitors' do
      resources :users
    end

    root 'dashboard#index'
  end

  scope module: 'visitors' do
    resources :users
    resource :sessions, only: [:new, :create, :destroy]
  end

  scope module: 'blog' do
    resources :articles, only: [:index, :show]
  end

  root 'dashboard#index'
end

app/views/common/_errors.html.haml
.bg-warning(style = 'padding: 10px; margin:15px 0')
  %button.close{ aria: { hidden: true } }
    &times;
  %h4 There are (#{object.errors.count}) errors exists :"
  - object.errors.full_messages.each do |msg|
    .text-danger= msg

app/views/common/_flash.html.haml
.container
  - flash.each do |key,value|
    = content_tag(:p, "Сообщение: #{value}", class: "lead text-center flash bg-danger")

app/views/common/_footer.html.haml
%p
  Blog template
  = DateTime.now

app/views/common/_header.html.haml
.container
  %nav.blog-nav
    %a.blog-nav-item.active{href: '#'} Home
    %a.blog-nav-item{href: '#'} Articles
    %a.blog-nav-item{href: '#'} Archieve
    %a.blog-nav-item{href: '#'} About

    .pull-right
      - if user_sign_in?
        You are sign in as:
        = link_to "#{current_user.login}(#{current_user.email})", current_user, class: 'blog-nav-item active'
        - if privileged_user?
          = link_to "To admin panel", admin_root_url, class: 'blog-nav-item active'
        = link_to "Exit", sessions_path, method: :delete, class: 'blog-nav-item active'
      - else
        = link_to "Sign in", new_sessions_path, class: 'blog-nav-item active'
        = link_to "Sign up", new_user_path, class: 'blog-nav-item active'