config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  # Admin namespace:
  namespace :admin do
    # (app/controllers/admin/blog/articles_controller.rb)
    scope module: 'blog' do
      resources :articles
      get 'tags/:tag', to: 'articles#index', as: :tag
      resources :categories
    end

    scope module: 'visitors' do
      resources :users
    end

    root 'dashboard#index'
  end

  scope module: 'visitors' do
    resources :users
    resource :sessions, only: [:new, :create, :destroy]
  end

  scope module: 'blog' do
    resources :articles, only: [:index, :show]
  end

  root 'dashboard#index'
end

app/models/category.rb
class Category < ActiveRecord::Base
  include DataHandler
  include Searchable

  VALID_CATEGORY_NAME = /\A\w+( -:()_\w+)*\Z/

  # Assosiation macros
  # -----------------------------------------------------------
  has_many :articles

  # Validates macros
  # -----------------------------------------------------------
  validates :name,
            presence:   true,
            length:     { maximum: 50 },
            uniqueness: { case_sensitive: false },
            format:     { with: VALID_CATEGORY_NAME }

  # Callbacks
  # -----------------------------------------------------------
  before_save   :input_data_handle

  # Scopes
  # -----------------------------------------------------------
  scope :display,           -> (display) { where display: display }
  scope :starts_with_name,  -> (name) { where('name like ?', "#{name}%") }

  protected

    def input_data_handle
      self.name = safe_str self.name
    end
end

app/controllers/admin/blog/articles_controller.rb
class Admin::Blog::ArticlesController < Admin::ApplicationController
  before_filter only: [:show, :edit, :update, :destroy] { |m| m.find_article params[:id] }

  def new
   @article = Article.new 
  end

  def create
    @article = @current_user.articles.new(article_params)
    if @article.save
      redirect_to admin_article_url(@article), notice: 'Article created!'
    else
      render :new
      flash.now[:error] = 'An error ocured on create article!'
    end
  end

  def show
  end

  def index
    if params[:tag]
      @articles = Article.tagged_with(params[:tag])
    else
      @articles = Article.includes(:category).
        search(params.slice(:archive, :starts_with_title)).
        filter(params[:filter]).
        all
    end
    @categories = Category.all
  end

  def destroy
    @article.destroy
    redirect_to admin_articles_url, notice: 'Article deleted!'
  end

  protected

    def article_params
      params.require(:article).permit(:title, :category_id, :contents, :all_tags)
    end

    def find_article id
      @article = Article.find(id)      
    end
end

app/controllers/admin/blog/categories_controller.rb
class Admin::Blog::CategoriesController < Admin::ApplicationController
  before_filter only: [:show, :edit, :update, :destroy] { |m| m.find_category params[:id] }

  def index
    @categories = Category.search(params.slice(:display, :starts_with_name)).all
  end

  def show
  end

  def edit
  end

  def update
    if @category.update_attributes(category_params)
      redirect_to admin_category_url(@category), notice: 'Category updated!'
    else
      render :edit
      flash.now[:error] = "Can't update category attributes!"
    end
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to admin_category_url(@category), notice: 'Category successfully created!'
    else
      render :new
      flash.now[:error] = 'Error on create category!'
    end
  end

  def destroy
    @category.destroy
    redirect_to admin_categories_url, notice: 'Category removed!'
  end

  protected

    def find_category id
      @category = Category.find(id)      
    end

    def category_params
      params.require(:category).permit(:name, :display)
    end
end

app/controllers/blog/articles_controller.rb
class Blog::ArticlesController < ApplicationController
  respond_to :json

  def index
    articles = Article.blog

    respond_with(articles) do |format|
      format.json { render json: articles.as_json }
    end
  end
end

app/views/admin/blog/categories/_category.html.haml
%tr
  %td
    %span.text-danger
      = category.name
  %td
    %span.label.label-success
      = category.articles.blank? ? 0 : category.articles.size
  %td
    %span.label.label-primary
      = category.display
  %td{colspan: 3}
    = link_to 'Show', admin_category_path(category), class: 'btn btn-default btn-xs'
    = link_to 'Delete', admin_category_path(category), method: :delete, class: 'btn btn-danger btn-xs', confirm: "Are you sure to delete #{category.name}?"
    = link_to 'Edit', edit_admin_category_path(category), class: 'btn btn-primary btn-xs'

app/views/admin/blog/categories/_category_articles.html.haml
/ Category articles list
%table.table.table-bordered
  %thead
    %th Title :
    %th Views :
    %th Published :
    %th Author :
    %th Created at :
    %th{colspan: 3} Actions :
  %tbody
    - articles.each do |article|
      %tr
        %td= link_to article.title, admin_article_path(article)
        %td
          %span.label.label-success
            = article.views
        %td
          %span.label.label-warning
            = article.published
        %td= article.author.login
        %td= date_format article.created_at
        %td{colspan: 3}
          = link_to admin_article_path(article), class: 'btn btn-default btn-xs' do
            %i.glyphicon.glyphicon-new-window
          = link_to admin_article_path(article), method: :delete, class: 'btn btn-danger btn-xs', confirm: "Are you sure to delete #{article.title}?" do
            %i.glyphicon.glyphicon-trash
          / = link_to 'Edit', edit_admin_articles_path(article), class: 'btn btn-primary btn-xs'

app/views/admin/blog/categories/_form.html.haml
= form_for [:admin, @category], html: { class: 'form form-horizontal', role: 'form' } do |f|
  = render 'common/errors', object: @category if @category.errors.any?
  .form-group
    = f.label :name, class: 'col-sm-1 control-label'
    .col-sm-6
      = f.text_field :name, class: 'form-control', required: true, autofocus: true
  .form-group
    .col-sm-offset-1
      %label.checkbox{ :for => "display" }
        = f.check_box :display, {checked: true}, true, false
        Visible
  .form-group
    .col-sm-offset-1
      = f.submit 'Create category', class: 'btn btn-success'
      = link_to 'Cancel', :back, class: 'btn btn-default'

app/views/admin/blog/categories/_search.html.haml
.btn-group
  = link_to new_admin_category_path, class: 'btn btn-success' do
    %i.glyphicon.glyphicon-plus Add
.btn-group
  %a.btn.btn-default{href: "#{admin_categories_path}"}
    Results, categories
    %span.badge= @categories.size
.btn-group
  %button.btn.btn-default Category display:
  %button.btn.btn-default{data: { toggle: 'dropdown' }}
    %span.caret
    %span.sr-only Category display
  %ul.dropdown-menu{role: 'menu'}
    %li= link_to 'Visible',   admin_categories_path(display: true)
    %li= link_to 'Disabled',  admin_categories_path(display: false)
    %li.divider
    %li= link_to 'All categories', admin_categories_path
.pull-right
  = form_tag admin_categories_path, method: :get, class: 'form form-inline', role: 'form' do
    = text_field_tag :starts_with_name, params[:starts_with_name], class: 'form-control', placeholder: 'name like...'
    = submit_tag 'Search', class: 'btn btn-success'

app/views/admin/blog/categories/edit.html.haml
%h1 Admin::Blog::CategoriesController#edit
%p Find me in app/views/admin/blog/categories_controller/edit.html.haml

app/views/admin/blog/categories/index.html.haml
%h2.text-info Categories list:
%hr
/ Categories search
= render 'search'
%hr
/ Categories list
- unless @categories.blank?
  %table.table.table-hover
    %thead
      %th Category name :
      %th Articles count :
      %th Category display :
      %th{colspan: 3} Actions :
    %tbody
      = render @categories
- else
  = render partial: 'admin/common/empty_resource'

app/views/admin/blog/categories/new.html.haml
%h2
  %i.glyphicon.glyphicon-plus-sign
  Adding category:
%hr
= render 'form'

app/views/admin/blog/categories/show.html.haml
%h1
  %i.glyphicon.glyphicon-folder-open
  = "Category '#{@category.name}'"
.pull-right
  = link_to 'Edit', admin_category_path(@category), class: 'btn btn-primary'
  = link_to 'Delete', admin_category_path(@category), method: :delete, class: 'btn btn-danger'
%hr
  %p.text-info= "Category name: '#{@category.name}'"
  Display category:
  %span.label.label-primary
    = @category.display
%hr
  %h2
    Category articles :
    %span.label.label-success
      = @category.articles.size
  - if @category.articles.blank?
    %p.text-danger
      There are no articles yet, please
      = link_to 'Add article', new_admin_article_path
  - else
    = render partial: 'category_articles', locals: { articles: @category.articles }